version: '3.8'

services:

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - micro-net

  payments:
    build: ./payments
    container_name: payments
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
      - rabbitmq
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
    networks:
      - micro-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # para la app
      - "15672:15672"   # para la consola web
    networks:
      - micro-net

networks:
  micro-net:
    driver: bridge
