spring:
  config:
    import: "optional:configserver:"  # Corregido ("sconfigsserver" ? "configserver")
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
      discovery:
        serviceId: config-service
        enabled: true
    gateway:
      server:
        webflux:
         routes:
           - id: checkout-service
             uri: lb://CHECKOUT-SERVICE  # Corregido ("lib:/@checkout-service" ? "lb://CHECKOUT-SERVICE")
             predicates:
               - Path=/checkout/**  # Añadido "/**" para capturar subrutas
             filters:
               - StripPrefix=0

server:
  port: 8084

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG