spring:
  config:
    import: "optional:configserver:"
  application:
    name: gateway-service
  cloud:
    config:
      enabled: false
      discovery:
        service-id: config-service
        enabled: true
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: checkout-service
              uri: lb://CHECKOUT-SERVICE
              predicates:
                - Path=/checkout/**
              filters:
                - StripPrefix=0
          httpclient:
            pool:
              max-idle-time: 5s

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true

server:
  port: 8084

management:  # Configuración de Actuator necesaria
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    reactor.netty.http.client: DEBUG